### ISSUE TITLE
Set `issued` key rather than `date` when formatting CSL output

### ISSUE THREAD

**Issue by coryschires** [inukshuk/anystyle#114]
## Problem
AnyStyle seems to do a very good job extracting publication date. But, based on my admittedly limited understanding of the CSL-JSON spec, AnyStyle does not set the correct key. 

Specifically, citeproc expects a nested `issued` key rather than a `date` key:

    # Something like...
    "issued" => { "date-parts" => [ [1998] ] }

    # Rather than...
    "date" => "1998"

## How to recreate

    raw_citation = %{Kessler, R.C. 1998. "Methodological Studies of the Composite International Diagnostic Interview" International Journal of Methods in Psychiatric Research 7 (1): 33-55. doi:10.1002/mpr.33.}

    metadata = AnyStyle.parse(raw_citation, format: :csl).first
    # => {
      :author => [{ :family => "Kessler", :given => "R.C." }],
      :date => "1998",
      :title => "Methodological Studies of the Composite International Diagnostic Interview",
      :volume => "7",
      :type => "article-journal",
      :"container-title" => "International Journal of Methods in Psychiatric Research",
      :issue => "1",
      :page => "33–55",
      :DOI => "doi:10.1002/mpr.33."
    }

## Desired behavior
While it's simple to convert `date` to `issued`, it would be wonderful if AnyStyle did this work for me.

**Comment by inukshuk** [comment]
Thanks, this is right.

By default we'll export `issued` as a string in ISO/EDTF since CSL wants to move in that direction; `citeproc-ruby` and `citeproc-js` should be able to parse most of these dates, but you can also export CiteProc's JSON format directly if you pass `date_format: 'citeproc'` to your call to `parse()`.

For the latter to work, please install the following gems: `citeproc`, `edtf`, and `chronic` -- the latter two are not strictly required but they will be used for parsing dates by the `citeproc` gem if available.

This will go into the next release; please also update `wapiti-ruby` to version 1.0.4.
