### ISSUE TITLE
Teaching Anystyle about "Heft" und "Jg"

### ISSUE THREAD

**Issue by a-fent** [inukshuk/anystyle#117]
Hallo - I would like to teach Anystyle about conventions occasionally used in German-language citations, namely "Jg" (Jahrgang) and "Heft" for volume and issue respectively. An example citation:

Reinermann, H.: Der Offentliche Sektor als Transformator in der Netzwerkgesellschaft. In: Verwaltung und Management. 10. Jg. (2004), Heft 4, S. 192-195. URL: http://www.dhv-speyer.de/rei/PUBLICA/online/cisco.pdf Abruf am: 17.03.2005

My local Anystyle instance with the default model makes a decent attempt, but doesn't get it quite right volume is parsed to ['10', '4'].

In the training dataset I can see some examples of this type in "ugly.xml", and presumably a little bit of work would be needed in normalizer/volume.rb, but I was wondering how you would like to handle this and if you would be open to patches?

**Comment by inukshuk** [comment]
Patches are definitely welcome! I'd suggest the following:

1. Add suitable patterns to the `keyword` feature [here](https://github.com/inukshuk/anystyle/blob/master/lib/anystyle/feature/keyword.rb#L36) -- since volume and issue are tagged together it is helpful if both `Heft` and `Jg` trigger the `volume` keyword.
2. Add a few samples to `core.xml` and `gold.xml` (ideally, a model trained using `core` should get all the samples in `gold` right).
3. Add rules to the volume normalizer to extract volume/issue correctly. I usually add some examples to the [specs](https://github.com/inukshuk/anystyle/blob/master/spec/anystyle/normalizer/volume_spec.rb) and then add the rules.

Step 1 above is not strictly necessary, but it should hep increase accuracy.

**Comment by a-fent** [comment]
This request was closed by https://github.com/inukshuk/anystyle/pull/118
