### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by tarwater** [inukshuk/anystyle#120]
Is the web service still issuing API keys?

**Comment by inukshuk** [comment]
If you would like one, yes.

However, I'd urge you to use the gem nowadays, because the web service still uses the 0.x branch. AnyStyle 1.0 is much improved, it should be much easier to install than it previously was (just `gem install anystyle anystyle-cli` on most platforms), and comes with a [CLI tool](https://github.com/inukshuk/anystyle-cli/) that covers most use cases (if you don't want to use the Ruby API). It also extracts references from PDF documents and it should give you much better and stable results than the web service.

**Comment by tarwater** [comment]
Well, I ask because it did not email me one. I understand the gem is better, I just want to use the web service temporarily and then migrate to the ruby application later.

**Comment by inukshuk** [comment]
Got it. An API key should be in the mail.

**Comment by NLPOR** [comment]
how to get the api service

**Comment by inukshuk** [comment]
There's no more API for public use.

The anystyle Ruby gem is much easier to install nowadays and the anystyle.io website itself has also been open sourced: using either of these should cover most use cases that relied on the API at a much higher quality.
