### ISSUE TITLE
Format "tags"

### ISSUE THREAD

**Issue by dominic01** [inukshuk/anystyle#139]
I am using very old version (0.8.2) of anystle parser in small script. Noted that it (and raw, xml) has been removed in the latest version. Is there a simple hack to get the tagged format? I am not using gem and using relative path.

**Comment by inukshuk** [comment]
We've abstracted some of these formats away and added them directly to `Wapiti::Dataset`. You can simply convert a dataset (that's the default result format) to real XML using `to_xml`; you can also pass options to `Builder` this way. For example, `dataset.to_xml(indent: 2)` and so on.

Basically, all the low-level outputs are pretty much still there, indirectly, but you can get at them via dataset (try: `to_xml`, `to_a`, `to_s`, `to_h`; either `to_a` or `to_s` is probably similar to what `raw` used to be). But if you're using this in a script, you may want to use the dataset itself: it comes with iterators and supports all set operations (i.e., you can easily compare, merge, diff results etc.).

**Comment by inukshuk** [comment]
You may want to look at [some of the examples in the tests](https://github.com/inukshuk/anystyle/blob/master/spec/anystyle/parser_spec.rb#L74). If you use `to_a` you'll probably want to pass `expanded: false` as an option (otherwise, if the dataset comes from the parser, it will include the full feature list for each token).
