### ISSUE TITLE
New Labels 

### ISSUE THREAD

**Issue by dominic01** [inukshuk/anystyle#145]
my Train.rb
```
require 'anystyle'
AnyStyle.parser.learn('/opt/ap_server/test.xml')
AnyStyle.parser.model.save('/opt/ap_server/sample.mod')
```

test.xml
[test.xml.txt](https://github.com/inukshuk/anystyle/files/4722387/test.xml.txt)

I am getting seg fault. Here I added a new label "mynote". I would like to add couple of new labels. Appreciate any pointers.

If I run the client, I dont get seg fault  but creates a mod. 
`anystyle --overwrite train test.xml sample.mod`

**Comment by inukshuk** [comment]
There are a number of known issues when appending to an existing model. One is that you can only use labels which are already known to the model.

To work around this, use the `train` method instead of `learn` in your example above. This will create an entirely new model based only on your test.xml. To build on the original model you can just merge your training set with core.xml.

**Comment by dominic01** [comment]
I didnt know the "learn" functionality is to append to an existing model. The `AnyStyle.parser.train` worked fine.
