### ISSUE TITLE
Training Json input

### ISSUE THREAD

**Issue by gjerome5** [inukshuk/anystyle#161]
Is it possible to train json data in anystyle. why type is only defined in json and not in xml output ?

**Comment by inukshuk** [comment]
It's possible but impractical to train JSON data. First off, the default JSON ouput of anystyle is CSL JSON. This is very different from the input, because many fields are normalized and may not correspond directly to tagged input. For training, it's important that the input corresponds to the training data. This is also the reason why `type` is not present in the XML (the main usage of the XML is training): there is typically no type in the input reference -- it's something that's guessed based on the reference's content.

So, yes, you could use JSON data for training (Wapiti Dataset can be serialized to Ruby Hashes, which can be mapped to JSON), but the JSON would look very different from CSL-JSON (and it would not include type either).

**Comment by gjerome5** [comment]
Thanks, what if we add type and train it in XML. Will it give proper results based on other elements. For eg book, we have publisher location, book title, publisher name etc. and why issue element is only available in xml and not in json ?

**Comment by inukshuk** [comment]
Yes, you can add new tags by creating training a new model based on training data which contains that tag. In my experience, it's a good idea to try to use as few tags as necessary, because having lots of similar-looking tags can make parse results much less predictable. Volume, issue, number, etc. is such an example: what we may refer to as volume, issue, report number, collection number, series, and so forth will often look much the same in a reference string. To differentiate between them, you usually need to know some context or the type of the reference -- this can often be done by looking at several meta-features, which is not easy to do in a CRF model. For this reason, we use a combined volume/issue tag in the training data and use a normalizer to map this to volume, issue, number, etc. fields.
