### ISSUE TITLE
Downloaded program to Interactive Ruby but cannot parse Chinese in it. UTF Issue?

### ISSUE THREAD

**Issue by pantsonfire** [inukshuk/anystyle#177]

**Comment by a-fent** [comment]
Hello - AnyStyle is based on classifying tokens (words) that are separated by whitespace. So while it could work with romanised Chinese, I don't think it will ever, in its current form, be able to support languages/scripts that don't work in this way, including traditional and simple Chinese.

I added some notes on natural languages in AnyStyle a few weeks ago: https://github.com/inukshuk/anystyle#natural-languages-used-in-anystyle

**Comment by a-fent** [comment]
If it's OK, I'm going to close this issue as it's (CANT|WONT)FIX.

It may be worth looking at other citation parsers or system that include citation parsing. AFAIK some take different approaches to tokenising.

In principle AnyStyle would work if there was some way to input chinese characters split up into word-tokens, but I don't understand enough about Chinese scripts to know if this is even possible.

**Comment by inukshuk** [comment]
Yes, this has come up a few times. It's possible to replace the current tokenizer with something more complex (the important thing is only that it works in the reverse so that the original reference can be reconstructed from training data; but in this case it would be trivial). To my knowledge Chinese word-segmentation is a problem that is similar in difficulty to reference parsing (if not harder) so this is not something that should be attempted by the AnyStyle parser itself; however, if we had a useful word-segmentation library in Ruby, I think it would be worthwhile to explore this further.

The tokenizer would need to switch (e.g., user option or automatically if there's no whitespace and characters of a given Unicode range occur). I think that would be enough to start training the model with real data. For better results, we'd likely also want to add language-specific hints to the feature extraction.

**Comment by pantsonfire** [comment]
I’d like to add that the problem is solved to a degree. It was originally working for me on any style.io but suddenly stopped working. I thought the site was down so I downloaded the ruby version. That then found this problem. 

I later found out the anystyle.io issue was it didn’t like traditional Chinese but was perfectly fine using simplified. So any style.io works perfect for simplified as long as there are some punctuation or spaces.

Wonder why?

thanks for the help!

**Comment by inukshuk** [comment]
That's great to hear. As we mentioned above, the model operates on the word tokens; this part currently depends on white-space (and to a degree to [certain punctuation](https://github.com/inukshuk/anystyle/blob/master/lib/anystyle/parser.rb#L114)). As long as the parser tokenizes your words (at least at the label-boundaries, i.e., between author, title, publication date and so on) this part should already work reasonably well.

To improve the results further we would need training data (perhaps you already marked some references for training online to get your results) and I'm certain the feature extraction would benefit from some patterns specific to Chinese, e.g. to detect features such as 'date', 'publisher', common names, etc.
