### ISSUE TITLE
Retrieve complete metadata online

### ISSUE THREAD

**Issue by albert-ying** [inukshuk/anystyle#185]
Hi, thank you for this amazing tool.

I was trying to convert the reference section of the papers to .bib file. And I realized the server only parse the information showed in the bibliography (e.g., some bibliography format only shows first author and other authors are missed in the record).

I’m wondering if it is possible to add option to try to retrieve the complete metadata from some online database, like what endnote do.

Thank you! (And if it is out of scope, could you let me know if there as any tool can be chained with anystyle to achieve this)

**Comment by inukshuk** [comment]
Hi! Querying an online database in order to retrieve canonical data for each reference is probably out of scope for this project. But I think it should be easy to do if you have a specific database: the anystyle CLI tool will give you either BibTeX or JSON data which should be easy to parse and convert into appropriate queries.
