### ISSUE TITLE
how can I make my gem installed version behave like the online anystyle.io

### ISSUE THREAD

**Issue by eliagbayani** [inukshuk/anystyle#203]
Is there a way to update some files on my local install of the anystyle gem so it parses the references
exactly the same as the web version anystyle.io ?
Thanks.

**Comment by inukshuk** [comment]
The model on anystyle.io can be changed by anyone at any moment, so the only way to do that would be to constantly sync the model files.

In practice, I think you'll get the best results by adding some of your own training data to the default set.

**Comment by eliagbayani** [comment]
@inukshuk,  thank you. 
Yes please how can I sync the model files of the anystyle.io to my local gem version?

**Comment by inukshuk** [comment]
You'd have to copy the file off the webserver, but that's not possible because we don't provide public access to the file.

But like I said, it would not be a practical solution anyway to sync to this version for your local use, because there is no quality assurance being done on the public model. It can be changed by anyone so it will be better or worse depending on the latest changes.

**Comment by inukshuk** [comment]
I guess the reason for your question is that you get better results online at the moment than with the default model. The best way to improve your local model then is to use exactly those results to train the model.

For example, let's say you have a sample of 10 references that are parsed exactly the way you want on anystyle.io but not with the default model. Then just download the XML results from anystyle.io, add them to the [core data set](https://github.com/inukshuk/anystyle/blob/master/res/parser/core.xml) and train a new model with it. This should improve your results in a controlled way.

**Comment by eliagbayani** [comment]
Thanks for the quick answer. That will work for me. I will do that.
