### ISSUE TITLE
ttx parser breaks if line doesn't end with space

### ISSUE THREAD

**Issue by cboulanger** [inukshuk/anystyle#208]
If in a `.ttx` file, a line does not end with a space (or is empty), the following error occurs:

```
Error: undefined method `gsub' for nil:NilClass
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/utils.rb:42:in `display_chars'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/page.rb:10:in `block in parse'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/page.rb:9:in `each'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/page.rb:9:in `parse'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/document.rb:62:in `pages'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/document.rb:67:in `each'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/finder.rb:33:in `with_index'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/finder.rb:33:in `block in expand'
        /var/lib/gems/3.0.0/gems/wapiti-2.0.0/lib/wapiti/dataset.rb:61:in `each'
        /var/lib/gems/3.0.0/gems/wapiti-2.0.0/lib/wapiti/dataset.rb:61:in `each'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/finder.rb:32:in `expand'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/parser.rb:86:in `prepare'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/finder.rb:88:in `prepare'
        /var/lib/gems/3.0.0/gems/anystyle-1.3.14/lib/anystyle/parser.rb:59:in `train'
        /app/cgi-bin/train.rb:55:in `<main>'
```

for example, the following line causes this to happen:

`blank         |\n` 

This is a problem because IDEs routinely strip trailing whitespace.

I've been working around this by programmatically adding spaces but I think it would be much better to fix the source of the problem, given that it should be really straightforward to make the parser more robust in this respect.

Thank you.

**Comment by inukshuk** [comment]
We're talking about the space after the `|` here, right?

While we can make the parser more lenient here, the reasoning behind this strictness was that we absolutely want to insure that the original input can be reconstructed. That means you should be able to strip the prefix on every line in order to get back the original input. If we allow variance here it becomes tricky: for example, for a line that has something like `blank    |     \n` in it, it will become impossible to know how many spaces there were before the newline in the original input.

In a sense it would be more useful to have no space after the `|` but with the space it's more pleasing on the eyes. The TTX format wasn't really planned as a format, it's something that evolved while trying to quickly tag documents by hand. So instead of trying to make this work I guess it would be better to switch to XML.

**Comment by cboulanger** [comment]
My preference would still be allowing no space since it is just syntax, isn't it? No information is lost since no space means the line is blank, with or without the space. If that's not what you want, please add a rescue section which throws an error that indicates which line is the problem, so that one has a chance to find the document and fix it. As it is right now, I (and others) have no clue what is causing the problem, it took me quite a while to understand why the error occurred at all.

Switching  to XML would certainl be preferrable since also this would allow to use transformed TEI documents (i.e. from GROBID). However, this would mean that I have to rewrite quite a bit of my app and I'd rather avoid that at this point.

**Comment by cboulanger** [comment]
great, thank you!
