### ISSUE TITLE
Automated generation of training data

### ISSUE THREAD

**Issue by philgooch** [inukshuk/anystyle#26]
Hi there - great tool! Have you considered automating the creation of training data from PubMed .nxml files, which you can get from ftp.ncbi.nlm.nih.gov/pub/pmc/.

The data is normalised, but could be extracted/transformed into the format required for training the parser according to different journal/citation styles.

**Comment by philgooch** [comment]
Having done some quick tests on this, I think you are right. The automated training data tends to be too uniform, and performance seems to degrade when parsing non-standard data. I've not quantified this though.

One useful thing I found though is if you ensure that the citation string ends in a full point, then parsing of volume and page number fields improves. Again, not quantified, but an observation.

**Comment by inukshuk** [comment]
Do you mean to say that if the entire string ends with a full point volume and page number recognition improves regardless of where these numbers are located in the string? Or is that only with either of the numbers located at the end of the string?

The parser splits the string into tokens (basically each word) and looks at the features of each word. We have a few features that analyze punctuation (this is pretty important for citations obviously) and also a feature which is basically just the value of the last character of the token. Therefore, a token like `42.` is much more 'characteristic' than `42` and much more likely to be recognized as a page number or volume since both often end with a period in our training data.

By the way, if you are looking for non-uniform training data, we have a lot of data collected from user inputs at anystyle.io -- these have not been curated, but it is much quicker to pick and normalize a data set based on those inputs than to create training data from scratch.

**Comment by philgooch** [comment]
Yes, it normally seems to improve things when the terminating token is a page number. For example, the reference

Chen, H., Tafalla, M., Greene, T. P., Myers, P. C., & Wilner, D. J. 1997, ApJ,475,163

gets parsed as

@misc{chen1997a,
  author = {Chen, H. and Tafalla, M. and Greene, T.P. and Myers, P.C. and Wilner, D.J.},
  year = {1997},
  note = {ApJ, 475, 163}
}

but adding a terminating period improves the parse to:

@article{chen1997a,
  author = {Chen, H. and Tafalla, M. and Greene, T.P. and Myers, P.C. and Wilner, D.J.},
  year = {1997},
  journal = {ApJ},
  volume = {475},
  pages = {163}
}

However, if the terminating token is a DOI then adding a period seems to often make things worse. So a simple heuristic that can improve the parse is to do something like match on \d+-\d+\s*$ and add the period at the end in these cases.

**Comment by inukshuk** [comment]
Do you have spaces between `AppJ,` `475,` and `163`?

This style is a bit tricky, because it is difficult to differentiate between volume and page numbers -- but I would expect this to work well given some training input. If you also add a few entries with DOIs and examples both with and without a terminating full stop I'd imagine the results to improve.
