### ISSUE TITLE
Make it easier to train and load model from training data

### ISSUE THREAD

**Issue by a-fent** [inukshuk/anystyle#78]
At the moment, it is hard to create an "empty" parser, train a new wapiti model, then use it. This is because a default path to the default model is set, the `initialize` method calls `reload`, and `train` is an instance method.

This makes it easy to use the default model - but only if everything goes right. If the default model doesn't load, it's hard to step through or see what's happening. Also, I think there might be some "user education" value in seeing e.g. in the README examples of models being loaded / saved / trained to understand better what is happening inside the parser.

My suggestion would be either to remove `reload` from the `initialize` method (this is what I did in my fork), or, as a compromise, perhaps add `Anystyle::Parser.load` and `Anystyle::Parser.train_new` module methods to easy working with custom data.

If you're open to one of these suggestions, I'm happy to prepare a patch.

PS: this might help (esp. if included in the documentation) with queries like this issue: https://github.com/inukshuk/anystyle-parser/issues/72

**Comment by inukshuk** [comment]
Absolutely. It is has been a long time, but I'm guessing my reasoning against an empty parser was that we'd never have to guard against missing models in any of the instance methods (that may not be a huge win though). Anyway, PR welcome any time -- I'll be working with the parser in the near future (mostly adding a new separate 'finder' component to detect references in full texts and feed them to the parser) so there are many changes imminent. That means you don't have to worry about backwards compatibility at all, because the next version we release will definitely be a major release anyway.

**Comment by a-fent** [comment]
That's all great to hear - especially interested to hear of the new 'finder' component. This DFG project has some initial results (I haven't seen myself) https://west.uni-koblenz.de/de/research/excite . It's something we would be interested in testing.

I'll submit a PR for the API changes shortly.

**Comment by inukshuk** [comment]
Oh, interesting. Are you involved in this project? It's basically what I'm currently working on (a line-based CRF model for finding the reference sections in full-texts); there's nothing there to see at the moment, but this will go into the [anystyle-finder](https://github.com/inukshuk/anystyle-finder) repository.

**Comment by a-fent** [comment]
No, I'm not involved in that project, but the functionality is of interest for us in our research projects here: http://www.dzhw.eu/abteilungen/system
