### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by dominic01** [inukshuk/anystyle#94]
Noted few updates in the last couple of months and do you have a change log (or release notes) file for our reference. I am using anystyle-parser in a small local setup and wondering if it would affect the recent changes.

**Comment by inukshuk** [comment]
We're in the process of rewriting large parts of the parser (and adding features); we'll update the documentation once the new changes are stable, but the new version will not be backwards compatible. (No reason to upgrade though, but if you do upgrade, you'll get a much improved parser)

**Comment by dominic01** [comment]
This is indeed a great news. 
Hope I can try the new changes now? I understand the current version is currently unstable.

**Comment by inukshuk** [comment]
You can use the latest version in `master` if you're interested. The parser itself is stable, but the outward facing API is likely to change and you're advised to look at the source code (and tests) for examples, because the readme does not reflect any of the changes yet and will be misleading. One of the biggest changes is that we're now using proper classes to manage data sets -- there are [some examples in this thread here](https://github.com/inukshuk/anystyle-parser/pull/89) that should help you get started, but I'm afraid there is not much more in terms of documentation at this time.
